[package]
name = "jpegxl-sys"
version = "0.1.0"
authors = ["Inflation <hypernovagama@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.54.1"
cmake = { version = "0.1.44", optional = true }

[features]
default = ["cmake"]
use-system-lib = []