[package]
name = "jpegxl-sys"
version = "0.1.0"
description = "Rust wrapper for JPEG XL reference implementation"
authors = ["Inflation <hypernovagama@gmail.com>"]
edition = "2018"
license = "GPL-3.0-or-later"
readme = "README.md"
repository = "https://github.com/inflation/jpegxl-sys"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
bindgen = "0.54.1"
cmake = { version = "0.1.44", optional = true }
pkg-config = { version = "0.3.18", optional = true }

[features]
default = ["pkg-config"]
build-jpegxl = ["cmake"]